name: Test Report
on:
  pull_request:
jobs:
  report:
    name: Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          junit-path: ./__tests__/data/junit_failure.xml
          coverage-path: ./__tests__/data/coverage.xml
